# Issue60
kapicorp/kapitan-reference pull request #61
Opened 2021-02-02 07:09 UTC by Moep90

Adds ability to specify readOnly: true/false with configmaps + secrets

2021-02-02 07:11 UTC, Moep90 commented
I might make sense to specify readOnly: `True` as a default value

2021-02-02 13:13 UTC, ademariag requested changes

2021-02-02 13:13 UTC, ademariag commented on components/generators/manifests/resources.libsonnet
> +        readOnly: utils.objectGet(config, 'readOnly'),
`utils.objectGet(config, 'readOnly', True)`?

2021-02-22 09:51 UTC, ademariag commented on components/generators/manifests/resources.libsonnet
> +        readOnly: utils.objectGet(config, 'readOnly'),
@Moep90 you marked as resolved, but I do not see an update. Did you forget to push?

2021-02-28 08:29 UTC, merged